- name: RabbitMQ | setting up ha on queue(s)
  rabbitmq_policy:
      name: 'ha-all'
      pattern: '.*'
      vhost: '{{ rabbitmq_vhost_name }}'
      tags: ha-mode=all, ha-sync-mode=automatic
      state: present
  delegate_to: "{{ groups[rabbitmq_group][0] }}"
  run_once: true
