- name: Install debian-archive-keyring and apt-transport-https packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - debian-archive-keyring
    - apt-transport-https

- name: Add RabbitMQ Erlang repository GPG Key
  apt_key:
    state: present
    url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc

- name: Add RabbitMQ repository GPG Key
  apt_key:
    state: present
    url: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey

- name: Add RabbitMQ Erlang repository
  apt_repository:
    repo: ppa:rabbitmq/rabbitmq-erlang
    state: present

- name: Add RabbitMQ repository
  apt_repository:
    repo: "deb https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu {{ansible_distribution_release}} main"
    state: present

- name: Install RabbitMQ
  package:
    name: rabbitmq-server
    state: present
