- name: Install debian-archive-keyring and apt-transport-https packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - debian-archive-keyring
    - apt-transport-https

- name: Add RabbitMQ Erlang repository GPG Key
  apt_key:
    state: present
    url: https://packagecloud.io/rabbitmq/erlang/gpgkey

- name: Add RabbitMQ repository GPG Key
  apt_key:
    state: present
    url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc

- name: Add RabbitMQ Erlang repository
  apt_repository:
    repo: deb https://packagecloud.io/rabbitmq/erlang/ubuntu bionic main
    state: present
    # filename: rabbitmq-erlang

- name: Add RabbitMQ repository
  apt_repository:
    repo: deb https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu bionic main
    state: present
    # filename: rabbitmq-server

- meta: end play

- name: Install RabbitMQ
  package:
    name: rabbitmq-server-3.7*
    state: present
