---
# TODO: Remove once ansible fixes their rabbitmq_user module, otherwise it will flag management user add as changed
- name: RabbitMQ | Check for management user
  shell: "rabbitmqctl list_users | grep '^{{ rabbitmq_mgmt_user }}'"
  register: rabbitmq_list_users
  delegate_to: "{{ groups[rabbitmq_group][0] }}"
  run_once: true
  ignore_errors: true
  changed_when: rabbitmq_mgmt_user not in rabbitmq_list_users.stdout
  check_mode: no

- name: RabbitMQ | Add management user
  rabbitmq_user:
    user: "{{ rabbitmq_mgmt_user }}"
    password: "{{ rabbitmq_mgmt_password }}"
    tags: administrator, "{{ rabbitmq_mgmt_user }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  delegate_to: "{{ groups[rabbitmq_group][0] }}"
  run_once: true
  when: (rabbitmq_mgmt_user not in rabbitmq_list_users.stdout) and
        ("administrator" not in rabbitmq_list_users.stdout)

- name: RabbitMQ | creating vhost
  rabbitmq_vhost:
      name: "{{ rabbitmq_vhost_name }}"
  delegate_to: "{{ groups[rabbitmq_group][0] }}"
  run_once: true

- name: RabbitMQ | creating user
  rabbitmq_user:
      user: "{{ rabbitmq_user }}"
      password: "{{ rabbitmq_password }}"
      vhost: "{{ rabbitmq_vhost_name }}"
      permissions:
          - vhost: "{{ rabbitmq_vhost_name }}"
            configure_priv: .*
            read_priv: .*
            write_priv: .*
      state: present
  delegate_to: "{{ groups[rabbitmq_group][0] }}"
  run_once: true
### TODO Check https://github.com/ansible/ansible/pull/50381 If it's been merged, remove ignore_errors
  ignore_errors: true
