- name: Copy config file for EC2 clustering
  template:
    src: etc/rabbitmq/rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
    owner: "{{ rabbitmq_linux_user }}"
    group: "{{ rabbitmq_linux_user }}"
    mode: 0660
  notify: restart rabbitmq

- name: Set erlang cookie
  template:
    src: var/lib/rabbitmq/.erlang.cookie.j2
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq
    group: rabbitmq
    mode: 0400