---
- name: RabbitMQ | Add management user
  rabbitmq_user:
    user: "{{ rabbitmq_mgmt_user }}"
    password: "{{ rabbitmq_mgmt_password }}"
    tags: administrator, "{{ rabbitmq_mgmt_user }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  run_once: true

- name: RabbitMQ | creating vhost
  rabbitmq_vhost:
      name: "{{ rabbitmq_vhost_name }}"
  delegate_to: "{{ groups['rabbitmq'][0] }}"
  run_once: true

- name: RabbitMQ | creating user
  rabbitmq_user:
      user: "{{ rabbitmq_user }}"
      password: "{{ rabbitmq_password }}"
      vhost: "{{ rabbitmq_vhost_name }}"
#      configure_priv: .*
#      read_priv: .*
#      write_priv: .*
      permissions:
          - vhost: "{{ rabbitmq_vhost_name }}"
            configure_priv: .*
            read_priv: .*
            write_priv: .*
      state: present
  delegate_to: "{{ groups['rabbitmq'][0] }}"
  run_once: true
  ignore_errors: true
