---
- name: Enable and Start RabbitMQ Service
  systemd:
    name: rabbitmq-server
    enabled: true
    state: started

#- name: Start RabbitMQ Service
#  systemd:
#    name: rabbitmq-server
#    state: started